services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 4080:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: task-app
    external: true
